total_iters: 200000000
output_dir: output_orig_hq_lr_0.001
checkpoints_dir: checkpoints_orig_hq_0.001

model:
  name: Wav2LipModelHq
  syncnet_wt: 0.
  disc_wt: 0.07
  max_eval_steps: 700
  generator:
    name: Wav2Lip
  discriminator_sync:
    name: SyncNetColor
  discriminator_hq:
    name: Wav2LipDiscQual
  wandb_group: "ddp-main-bs-8-original"

export_model:
  - {name: 'netG', inputs_num: 2}

dataset:
  train:
    name: Wav2LipDataset
    dataroot: /mnt/disks/sdc/lrs2-main-preprocessed
    filelists_path: ./
    img_size: 96
    split: train
    batch_size: 32
    num_workers: 4
    use_shared_memory: False
  test:
    name: Wav2LipDataset
    dataroot: /mnt/disks/sdc/lrs2-main-preprocessed
    filelists_path: ./
    img_size: 96
    split: val
    batch_size: 16
    num_workers: 4
    use_shared_memory: False

optimizer:
  optimizer_G:
    name: Adam
    net_names:
      - netG
    beta1: 0.5
  optimizer_DS:
    name: Adam
    net_names:
      - netDS
    beta1: 0.5
  optimizer_DH:
    name: Adam
    net_names:
      - netDH
    beta1: 0.5

validate:
  interval: 3000
  save_img: false

lr_scheduler:
  name: LinearDecay
  learning_rate: 0.001
  start_epoch: 2000000
  decay_epochs: 2000000
  # will get from real dataset
  iters_per_epoch: 1

log_config:
  interval: 10
  visiual_interval: 500

snapshot_config:
  interval: 3000
